### ISSUE TITLE
Thank you for your effort

### ISSUE THREAD

**Issue by GrahamBriggs** [woodenphone/lego_dimensions_protocol#6]
This is not an issue, just using the tracker to write a thank you note.

I was trying to find a use for the kids' old Lego Dimensions portal for something new we could make. I came across your code and was grateful to find out you had done all the hard work of sniffing out the protocol.

My projects are in C/C++ or C#, so I had to port it over to a C++ library with a simple C API.h.  However, this was an easy paint by number job thanks to your prior work. You may see the results [here](https://github.com/GrahamBriggs/liblegodimensionsportal)

I just wanted to pass along my gratitude and let you know that your effort benefited one more person in the world.

Cheers

GB

**Comment by woodenphone** [comment]
I'm glad that you found my code useful.
It always feels great to see someone using something I worked on.
